### ISSUE TITLE
Errors when updating many files

### ISSUE THREAD

**Issue by billyvg** [getsentry/action-github-commit#1]
We need to look into handling a large number of files as we currently have errors due to wrong commit SHA being used when we update multiple files (missing `await` somewhere).

We also will hit API limits as well because we are creating a new commit per file. We should look into using bulk commits, maybe using the [git data API](https://docs.github.com/en/rest/reference/git).

**Comment by chadwhitacre** [comment]
Seems like this might be what I'm hitting on https://github.com/getsentry/security-as-code/pull/90.

**Comment by chadwhitacre** [comment]
Here's [a case](https://github.com/getsentry/security-as-code/pull/110/commits) where we had 200+ files to update and it took a looooong time.

**Comment by chadwhitacre** [comment]
[Not out of the woods](https://github.com/getsentry/action-github-commit/actions/runs/4960344243/jobs/8875698572#step:6:22):

```
RequestError [HttpError]: is at 89b4e1b16b8bf61b55f6163e2860c3ac623c8cdb but expected 5d625416bd260bb2b6e5ed078a07622d889b1106
```

This is on #15.

**Comment by chadwhitacre** [comment]
I'm almost positive it's running the old version of the action, I [changed](https://github.com/getsentry/action-github-commit/pull/13/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dL37) this [`error?` debug line](https://github.com/getsentry/action-github-commit/actions/runs/4960344243/jobs/8875698572#step:6:22).

**Comment by chadwhitacre** [comment]
Is the `dist/index.js` not getting updated properly?

**Comment by chadwhitacre** [comment]
Yeah this is wrong:

https://github.com/getsentry/action-github-commit/blob/5750839687891f6992a52fd0403833539ece4c5e/dist/index.js#L91

**Comment by chadwhitacre** [comment]
Ah, yeah, okay. Here's the dist on #11:

https://github.com/getsentry/action-github-commit/blob/ed3c2970b1946ed4d994cdc3a30fa3caf40f24fc/dist/index.js#L91

I guess what's happening is that since the action is running on main even when triggered in a PR, we end up never updating dist essentially. Branch challenge. 🤔

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/action-github-commit/pull/16 should close this.
